name: Build Release Next.js web Application
on: 
  workflow_dispatch:

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install NPM Dependencies
      run: npm install
    - name: Build project Assets
      run: npm run build
    - name: Upload Static site content
      uses: actions/upload-artifact@v4
      with:
         name: static-site
         path: ./next-web-app
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
         name: static-site
    - name: Test artifact download
      run: ls -R
    - name: Archive site content
      uses: thedoctor0/zip-release@main
      with:
        filename: site.zip
    - name: Create GitHub Release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: Uploade release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./site.zip
        asset_name: site-v${{ github.run_number }}.zip
        asset_content_type: application/zip
  

      